name: Develop Branch Workflow

on:
   push:
    branches: [ develop, main ]
    paths-ignore:
    - '.github/**'


jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup & Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Build
        run: echo "Running install with GPR Token"; npm install; npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
      - name: Run Unit Tests
        run: npm run test

